### ISSUE TITLE
Dependencies are broken

### ISSUE THREAD

**Issue by sebastianbarfurth** [eltrino/DiamanteDeskBundle#1]
Installation for development and testing purposes is impossible.

**Comment by odi-um** [comment]
Hi, 

Unfortunately there are not stable release yet. To be able install current development version you will need to set allowed 'minimum-stability' to 'dev'. This could be done in your root composer.json file. More information you could find [here](https://getcomposer.org/doc/04-schema.md#minimum-stability).

**Comment by anedisi** [comment]
cleared the cache and still getting.

```
[2015-07-23 23:39:25] request.CRITICAL: Uncaught PHP Exception Oro\Bundle\EntityConfigBundle\Exception\RuntimeException: "Entity "Diamante\DeskBundle\Entity\Branch" is not configurable" at /Applications/MAMP/htdocs/temp/oro/crm-application/vendor/oro/platform/src/Oro/Bundle/EntityConfigBundle/Config/ConfigManager.php line 260 {"exception":"[object] (Oro\\Bundle\\EntityConfigBundle\\Exception\\RuntimeException: Entity \"Diamante\\DeskBundle\\Entity\\Branch\" is not configurable at /Applications/MAMP/htdocs/temp/oro/crm-application/vendor/oro/platform/src/Oro/Bundle/EntityConfigBundle/Config/ConfigManager.php:260)"} []
```

**Comment by northdakota** [comment]
Hi Anedisi,
Could your to specify:
1. What version of diamantedesk your use
2. What way your use to install diamantedesk,

if your have a fresh installation try to clear caches and run next command
php app/console doctrine:schema:update --force
from the root directory

Thx, for response.

**Comment by anedisi** [comment]
it is a brand new installation orocrm 1.7.*. 
php app/console doctrine:schema:update --force did not help.
still the same isssue

**Comment by kstupak** [comment]
Hi Anedisi!

First things first - it would be lovely, if you could create separate issue for your problem, as this one is not relevant.

Secondly, try running 
```app/console oro:platform:update --force --timeout=0``` 

It appears to be that your entity config cache is not updated therefore system is not able to process entities correctly.

**Comment by anedisi** [comment]
i ran that and still got the same message.
i switched to dev envirement and now i can get in but im not sure is everything installed.
should there be something in the menu ? i got nothing. only a support dashboard and when i try to ad something to dashboard i get this

```
Uncaught Error: The route "diamante_report_widget" does not exist.
```
sorry about opening old issue i will open a different when i have little more time.

**Comment by kstupak** [comment]
@anedisi if you are installing DiamanteDesk on top of existing OroCRM instance, you should install our integration package via composer as follows:
``` composer require diamante/orocrm-integration-bundle:dev-master ```

The package installed will pull all the requirements by itself, and then you should run following commands:

```app/console diamante:desk:install```
```app/console diamante:user:install```
```app/console assets:install --symlink```
```app/console diamante:front:build --with-assets-dependencies```
```app/console assetic:dump```
```app/console cache:clear --no-warmup ```

We are working on installation guide for this use case and will notify you, when it will be ready. 
For now please refer to instructions above.

If you are installing DiamanteDesk as a standalone application (no OroCRM installed, only Oro Platform), then please refer to [this](http://docs.diamantedesk.com/en/latest/installation-guide/installation/) guide.
