### ISSUE TITLE
Does it work with Oroplatform 1.6.*?

### ISSUE THREAD

**Issue by mingxing** [eltrino/DiamanteDeskBundle#2]
Hi

I installed Orocrm, and tried to install this ticket management system, but I got:
  Problem 1
    - Can only install one of: oro/platform[1.4.x-dev, 1.6.1].
    - Can only install one of: oro/platform[1.6.1, 1.4.x-dev].
    - diamante/desk-bundle dev-master requires oro/platform 1.4.* -> satisfiable by oro/platform[1.4.x-dev].

Does it work with Oroplatform 1.6.*?
Best Regards
Simon

**Comment by odi-um** [comment]
Hi Simon,

Currently we're testing on 1.4 only. Our plan is to support the latest Oro Platform (probably it could be even 1.7) till the stable release of DiamanteDesk 1.0.

This Stable version should be ready in next months. Stay tuned!

**Comment by sibben** [comment]
Can we expect to run DiamanteDesk on  OroCRM 1.7 soon?

**Comment by northdakota** [comment]
Hi Sibben,
At this moment we support 1.7 and 1.7.1 version. So you can try it.

**Comment by sibben** [comment]
That's great, but.....

When i run  ```` composer require diamante/desk-bundle:dev-master ````

i get 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - diamante/desk-bundle dev-master requires diamante/email-processing-bundle dev-master -> satisfiable by diamante/email-processing-bundle[dev-master].
    - Conclusion: remove oro/platform 1.x-dev
    - Installation request for diamante/desk-bundle dev-master -> satisfiable by diamante/desk-bundle[dev-master].
    - Conclusion: don't install oro/platform 1.x-dev
    - Conclusion: don't install oro/platform 1.x-dev
    - diamante/email-processing-bundle dev-master requires oro/platform 1.7.* -> satisfiable by oro/platform[1.7.x-dev].
    - Can only install one of: oro/platform[1.7.x-dev, 1.x-dev].
    - Can only install one of: oro/platform[1.7.x-dev, 1.x-dev].
    - Installation request for oro/platform 1.x-dev -> satisfiable by oro/platform[1.x-dev].

Installation failed, reverting ./composer.json to its original content.

**Comment by northdakota** [comment]
Hi Sibben,
I have installed OroCRM 1.7.0 and also have installed DiamanteDesk by following command
`composer require diamante/desk-bundle:dev-master`

```
northdakota@northdakota-pc:~/oro-1.7$ composer require diamante/desk-bundle:dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

  - Installing diamante/user-bundle (dev-master b432c0f)
    Cloning b432c0fd942ac9ab27a487f6b529b967ab39aaec

  - Installing diamante/api-bundle (dev-master c86b306)
    Cloning c86b3066cd35070d5360ef94a88ac5d91efc197d

  - Installing electrolinux/phpquery (0.9.6)
    Loading from cache

  - Installing bordeux/email-cleaner (dev-master 8a56eaf)
    Cloning 8a56eaff0b2aac97958734f4e7c573e7b3bd37e3

  - Installing beberlei/assert (v2.3)
    Loading from cache

  - Installing diamante/email-processing-bundle (dev-master 63c3fec)
    Cloning 63c3fec16bdaa972001427ee70054571c316c125

  - Installing diamante/desk-bundle (dev-master 4b2540d)
    Cloning 4b2540d443d4716b4b625a4204a2f3ea38499a2d

Package rhumsaa/uuid is abandoned, you should avoid using it. Use ramsey/uuid instead.
Writing lock file
Generating autoload files
Compiling component files
Updating the "app/config/parameters.yml" file
```

And it was installed without any problem. 
I suggest that some versions of composer is broken, because i already seen the similar error before.

Could you to specify your composer version?
`composer --version`

Also you can try to switch composer to last stable version by next command
`composer self-update "1.0.0-alpha10"`
And try to install DiamanteDesk again.

Thanks!

**Comment by sibben** [comment]
I have Composer version 1.0-dev and I've switched to Composer version 1.0.0-alpha10  as you proposed. But the output of ```` composer require diamante/desk-bundle:dev-master ```` didn't change.

Then I looked a bit further and found that composer.json contained this

```` 
"oro/platform": "1.x-dev",
"oro/crm": "1.x-dev",
 ```` 
Don't know how it got there.
Changed it to 

````     
"oro/platform": "1.7.x-dev",
"oro/crm": "1.7.x-dev",

 ```` 

And voila!
