### ISSUE TITLE
'There are no commands defined in the "diamante:desk" namespace'

### ISSUE THREAD

**Issue by sibben** [eltrino/DiamanteDeskBundle#3]
I did a fresh install of OroCrm 1.7
Then ````  composer require diamante/desk-bundle:dev-master ````
So far so good...  
But ````  php app/console diamante:desk:install  ```` doesn't work.

The error is : There are no commands defined in the "diamante:desk" namespace

**Comment by northdakota** [comment]
Hi Sibben,
Do you clear the caches before that?
You need to remove next folders:
app/cache/dev
app/cache/prod
app/cache/test

**Comment by sibben** [comment]
Whoohoo! That fixed it
